# Generated by Django 3.1.3 on 2020-11-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0003_auto_20201109_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload file with material', upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_added', models.CharField(help_text='Username who added material', max_length=20)),
                ('date_publication', models.DateTimeField(help_text='Date and time for uploading')),
                ('image_preview_small', models.ImageField(default='home/static/home/images/thumbs/masonry/rucksack-600.jpg', help_text='Preview image (small)', upload_to='')),
                ('image_preview_big', models.ImageField(default='home/static/home/images/thumbs/masonry/rucksack-1200.jpg', help_text='Preview image (big)', upload_to='')),
                ('title', models.CharField(help_text='Enter title of material', max_length=100)),
                ('author', models.CharField(help_text='Enter author of material', max_length=100)),
                ('short_summary', models.CharField(default='Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim. ', help_text='Enter short summary of book, what is it about?', max_length=200)),
                ('description', models.CharField(default='Lorem ipsum Sed eiusmod esse aliqua sed incididunt aliqua incididunt mollit id et sit proident dolor nulla sed commodo est ad minim elit reprehenderit nisi officia aute incididunt velit sint in aliqua cillum in consequat consequat in culpa in anim. ', help_text='Enter description of book', max_length=200)),
                ('attachments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.filefield')),
                ('categories', models.ManyToManyField(help_text='Choose tags for book', to='category.Category')),
            ],
            options={
                'ordering': ['title', '-date_publication'],
            },
        ),
    ]
