# Generated by Django 3.1.3 on 2020-12-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('0', 'Invisible'), ('1', 'Approved'), ('2', 'Declined')], default='0', help_text='Current state of material', max_length=1),
        ),
    ]
