# Generated by Django 3.1.3 on 2020-12-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_visibility'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileField',
            new_name='MyFileField',
        ),
        migrations.RemoveField(
            model_name='post',
            name='short_summary',
        ),
    ]
