# Generated by Django 3.1.3 on 2020-12-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201216_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='attachments',
        ),
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(help_text='Choose attachments to post', to='post.MyFileField'),
        ),
    ]
