# Generated by Django 3.1.3 on 2020-11-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(help_text='Choose any categories book belongs', max_length=30),
        ),
    ]
