# Generated by Django 3.1.3 on 2020-11-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201109_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['text']},
        ),
    ]
